services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  api:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
      - uploads:/home/node/app/public/uploads   # <== Add this line
    working_dir: /home/node/app
    command: bash -c "npm install && node ace serve --watch"
    environment:
      HOST: 0.0.0.0
      PORT: 3333
      NODE_ENV: development
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    depends_on:
      - db

volumes:
  pgdata:
  pgadmin-data:
  uploads: